In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
import os
os.getcwd()

'C:\\Users\\Sushant Singh\\Desktop\\Ducat\\Vineet Sir Classes\\Handwritten digit recognizer'

In [22]:
ls

 Volume in drive C is OS
 Volume Serial Number is FAD7-FFA6

 Directory of C:\Users\Sushant Singh\Desktop\Ducat\Vineet Sir Classes\Handwritten digit recognizer

05/05/2019  10:49 AM    <DIR>          .
05/05/2019  10:49 AM    <DIR>          ..
05/05/2019  10:27 AM    <DIR>          .ipynb_checkpoints
05/05/2019  10:49 AM            12,645 Handwritten Digit Recognition.ipynb
05/05/2019  09:32 AM           240,909 sample_submission.csv
05/05/2019  09:34 AM        51,118,296 test (2).csv
05/05/2019  09:34 AM        76,775,041 train (1).csv
               4 File(s)    128,146,891 bytes
               3 Dir(s)  393,722,818,560 bytes free

In [23]:
train = pd.read_csv('train (1).csv')

In [24]:
train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
train.label.value_counts()

1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: label, dtype: int64

In [26]:
y_train = pd.DataFrame(train['label'],columns=['label'])
x_train = train.drop(labels=['label'], axis=1)

In [27]:
x_train.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
y_train.head()

   label
0      1
1      0
2      1
3      4
4      0

In [29]:
print(x_train.isnull().any())

pixel0      False
pixel1      False
pixel2      False
pixel3      False
pixel4      False
pixel5      False
pixel6      False
pixel7      False
pixel8      False
pixel9      False
pixel10     False
pixel11     False
pixel12     False
pixel13     False
pixel14     False
pixel15     False
pixel16     False
pixel17     False
pixel18     False
pixel19     False
pixel20     False
pixel21     False
pixel22     False
pixel23     False
pixel24     False
pixel25     False
pixel26     False
pixel27     False
pixel28     False
pixel29     False
            ...
pixel754    False
pixel755    False
pixel756    False
pixel757    False
pixel758    False
pixel759    False
pixel760    False
pixel761    False
pixel762    False
pixel763    False
pixel764    False
pixel765    False
pixel766    False
pixel767    False
pixel768    False
pixel769    False
pixel770    False
pixel771    False
pixel772    False
pixel773    False
pixel774    False
pixel775    False
pixel776    False
pixel777    False
pixel778    False
pixel779    False
pixel780    False
pixel781    False
pixel782    False
pixel783    False
Length: 784, dtype: bool